Create portfolio webpage for large screens
tacettinkustu/My-Portfolio-Website pull request #10
Opened 2021-06-09 12:14 UTC by tacettinkustu

Creating portfolio webpage for large screens consist of this phases :

1. Creating navbar
2. Creating header
3. Creating work cards
4. Creating footer

2021-06-09 18:23 UTC, MahmoudBakr23 requested changes
Hello @tacettinkustu 😃, 

Great work and effort you put into this project so far.

## Highlights 🚀 

There are some excellent points that you have made perfectly. Keep up! 💪
- Linter is correct
- Good work following the design
- Descriptive PR summary and commit messages.

However, there is always room for improvement.

> Keep in mind that your long hours of work are appreciated. However, the code review process is for improving the code you wrote, and not for criticizing it. 😄

 ## Required Changes ♻️
_Please check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

N/A

Cheers and Happy coding!👏👨‍💻💻

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-06-09 18:23 UTC, MahmoudBakr23 commented on index.html
> +
- [x] Kindly delete this blank line here.
Please notice that we're only adding blank lines and indentations for good reasons such as keeping two logical pieces of code or two large sections apart from each other.

> You can read about this point and others at this [link](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/html_css_best_practices.md).

2021-06-09 18:23 UTC, MahmoudBakr23 commented on style.css
> +@media only screen and (min-width: 768px) {
- [x] Please follow the project requirements and modify this media query to match the desktop screen size (min-width > 992px - 1100px).

- [x] Also, this will help to keep the website from overflowing. _See the image down below._
![Screenshot 2](https://user-images.githubusercontent.com/47625407/121407598-c8a0f580-c95f-11eb-96f8-baea5b214494.png)

2021-06-09 18:23 UTC, MahmoudBakr23 commented on style.css
> +}
- [x] This element is causing extra space at the very bottom of the website. Let's work on that in order to follow the given design as much as we can.

_See images down below._
### **Your design**
![Screenshot1](https://user-images.githubusercontent.com/47625407/121408023-32210400-c960-11eb-9c47-d1b73b69829f.png)
### **[Original design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1)**
![Screenshot](https://user-images.githubusercontent.com/47625407/121408044-3b11d580-c960-11eb-99c4-6d5f93110a2d.png)

2021-06-10 06:15 UTC, tacettinkustu commented on index.html
> +
I deleted all unnecessary blank lines from my html file.

2021-06-10 06:20 UTC, tacettinkustu commented on style.css
> +@media only screen and (min-width: 768px) {
Okay. Thanks. I changed breakpoint for media queries.

2021-06-10 06:26 UTC, tacettinkustu commented on style.css
> +}
I displayed layer element for fixing this unnecessary space.

2021-06-10 06:39 UTC, Davidosky007 commented on style.css
> +@media only screen and (min-width: 768px) {
[OPTIONAL]
![Screenshot (36)](https://user-images.githubusercontent.com/52497246/121476579-befaaa80-c9be-11eb-9446-4ed4ef4b8ea5.png)

I can see Your portfolio website still overflow a little bit i suggest you use (overflow-x: hidden) to fix the scroll bar below your webpage 👍

2021-06-10 06:42 UTC, Davidosky007 commented
Hi @tacettinkustu, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![CR1 GIF](https://user-images.githubusercontent.com/52497246/121476982-30d2f400-c9bf-11eb-9472-d563793e3483.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-06-10 06:44 UTC, merged